# Generated by Django 6.0.1 on 2026-01-11 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='EexpenseCost',
            new_name='ExpenseCost',
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='EexpenseDate',
            new_name='ExpenseDate',
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='EexpenseItem',
            new_name='ExpenseItem',
        ),
    ]
